"""fixing

Revision ID: 07982c0e9bff
Revises: 53d528c903c3
Create Date: 2024-07-27 14:31:38.515606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '07982c0e9bff'
down_revision = '53d528c903c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ddoe', schema=None) as batch_op:
        batch_op.alter_column('previous_topics',
               existing_type=sqlite.JSON(),
               type_=sa.PickleType(),
               existing_nullable=True)
        batch_op.alter_column('previous_words',
               existing_type=sqlite.JSON(),
               type_=sa.PickleType(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ddoe', schema=None) as batch_op:
        batch_op.alter_column('previous_words',
               existing_type=sa.PickleType(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('previous_topics',
               existing_type=sa.PickleType(),
               type_=sqlite.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
