"""userpreference modification

Revision ID: 093045547e2f
Revises: 1ebec77ce3cb
Create Date: 2024-05-18 22:07:30.662992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093045547e2f'
down_revision = '1ebec77ce3cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strengths', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('weaknesses', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('weaknesses')
        batch_op.drop_column('strengths')

    # ### end Alembic commands ###
