"""hello

Revision ID: 0f5ccd3af244
Revises: 093045547e2f
Create Date: 2024-07-15 10:56:50.847271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5ccd3af244'
down_revision = '093045547e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('dailytopic', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('dailytopic')
        batch_op.drop_column('language')

    # ### end Alembic commands ###
