"""added daiy words

Revision ID: 1369f3157375
Revises: 99af02cecac5
Create Date: 2024-07-24 15:35:15.055354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1369f3157375'
down_revision = '99af02cecac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ddoe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_words', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ddoe', schema=None) as batch_op:
        batch_op.drop_column('previous_words')

    # ### end Alembic commands ###
