"""bye caching

Revision ID: 5a32206c5040
Revises: 98b757217612
Create Date: 2024-10-29 17:47:28.512731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a32206c5040'
down_revision = '98b757217612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ddoe_cache')
    op.drop_table('wotd_cache')
    op.drop_table('ddoe_reels_cache')
    op.drop_table('ddoe_articles_cache')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ddoe_articles_cache',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ddoe_topic', sa.VARCHAR(length=50), nullable=True),
    sa.Column('article_title', sa.VARCHAR(length=500), nullable=True),
    sa.Column('article_url', sa.VARCHAR(length=10000), nullable=True),
    sa.Column('article_text', sa.VARCHAR(length=10000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ddoe_reels_cache',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ddoe_topic', sa.VARCHAR(length=50), nullable=True),
    sa.Column('video_id', sa.VARCHAR(length=10000), nullable=True),
    sa.Column('video_title', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wotd_cache',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('word_age', sa.INTEGER(), nullable=True),
    sa.Column('word', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ddoe_cache',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('topic_age', sa.INTEGER(), nullable=True),
    sa.Column('topic_name', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
