"""added ddoe

Revision ID: 663b6deef516
Revises: 7a495d91e842
Create Date: 2024-06-14 13:21:02.939078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663b6deef516'
down_revision = '7a495d91e842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dailytopic', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('dailytopic')

    # ### end Alembic commands ###
