"""checking

Revision ID: 6a0f162e30c5
Revises: 5a32206c5040
Create Date: 2025-01-09 22:28:13.936716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.types import Text

# revision identifiers, used by Alembic.
revision = '6a0f162e30c5'
down_revision = '5a32206c5040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seen_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('past_articles', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('past_reels', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('past_topics', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('past_questions', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('past_words', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seen_content')
    # ### end Alembic commands ###
