"""TRYY

Revision ID: 931ba25e3b65
Revises: 9599afc03302
Create Date: 2024-07-27 15:05:52.455527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931ba25e3b65'
down_revision = '9599afc03302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ddoe', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ddoe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
