"""caching

Revision ID: 98b757217612
Revises: cbd165da2931
Create Date: 2024-10-29 17:35:20.104841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b757217612'
down_revision = 'cbd165da2931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ddoe_articles_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ddoe_topic', sa.String(length=50), nullable=True),
    sa.Column('article_title', sa.String(length=500), nullable=True),
    sa.Column('article_url', sa.String(length=10000), nullable=True),
    sa.Column('article_text', sa.String(length=10000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ddoe_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_age', sa.Integer(), nullable=True),
    sa.Column('topic_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ddoe_reels_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ddoe_topic', sa.String(length=50), nullable=True),
    sa.Column('video_id', sa.String(length=10000), nullable=True),
    sa.Column('video_title', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wotd_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_age', sa.Integer(), nullable=True),
    sa.Column('word', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wotd_cache')
    op.drop_table('ddoe_reels_cache')
    op.drop_table('ddoe_cache')
    op.drop_table('ddoe_articles_cache')
    # ### end Alembic commands ###
