"""added previous topoics

Revision ID: 99af02cecac5
Revises: a059613ce6c5
Create Date: 2024-07-24 15:12:03.159109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99af02cecac5'
down_revision = 'a059613ce6c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ddoe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_topics', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ddoe', schema=None) as batch_op:
        batch_op.drop_column('previous_topics')

    # ### end Alembic commands ###
