"""added streaks

Revision ID: a059613ce6c5
Revises: 5bffd1a5b1b1
Create Date: 2024-07-23 14:21:45.153733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a059613ce6c5'
down_revision = '5bffd1a5b1b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ddoe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_streak', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ddoe', schema=None) as batch_op:
        batch_op.drop_column('current_streak')

    # ### end Alembic commands ###
