"""definition

Revision ID: cc664efb95cb
Revises: 3c6dfc97cc87
Create Date: 2024-07-27 15:35:37.753848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc664efb95cb'
down_revision = '3c6dfc97cc87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ddoe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('definition', sa.String(length=5000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ddoe', schema=None) as batch_op:
        batch_op.drop_column('definition')

    # ### end Alembic commands ###
